/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sergi
 */
public class jfrmPrestamo extends javax.swing.JFrame {
    // Atributos de la lógica del préstamo
    private double credito;
    private int periodoMax, periodoMin;
    private double interesMin, interesMax;
    private double incremento;
    private int tiposIntrs, añosMeses;
    private boolean tablaPagos;
    private double pagoMensual;
    private javax.swing.JTable jtablaPrestamo;
    private javax.swing.JTable jtablaCabsFilas;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jfrmPrestamo.class.getName());

    /**
     * Creates new form jfrmPrestamo
     */
    public jfrmPrestamo() {
        initComponents();
        this.setSize(600,450);
        this.setLocationRelativeTo(null);
        jtfCredito.setEditable(true);
        jtfCredito.setEnabled(true);
        tiposIntrs = 18;
        añosMeses = 4;
        jmItemAños.setEnabled(false);
        initTable(tiposIntrs, añosMeses + 1);
        
    }
    private void initTable(final int filasTabla, final int colsTabla) {
        class CModeloTablaPrestamo extends javax.swing.table.AbstractTableModel {
            Object dato[][] = new Object[filasTabla][colsTabla];
            String cabecera[] = new String[colsTabla];

            CModeloTablaPrestamo() {
                cabecera[0] = "Interés";
                for (int c = 1; c < colsTabla; ++c) {
                    cabecera[c] = c + " año" + (c > 1 ? "s" : "");
                }
            }

            public int getColumnCount() { return cabecera.length; }
            public int getRowCount() { return dato.length; }
            public String getColumnName(int col) { return cabecera[col]; }
            public Object getValueAt(int fila, int col) { return dato[fila][col]; }
            public void setValueAt(Object obj, int fila, int col) { dato[fila][col] = obj; }
            public boolean isCellEditable(int indFila, int indColum) { return false; }
        };

        javax.swing.table.TableColumnModel modeloColums = new javax.swing.table.DefaultTableColumnModel() {
            boolean primeraCol = true;
            public void addColumn(javax.swing.table.TableColumn col) {
                if (primeraCol) { primeraCol = false; return; }
                col.setMinWidth(110);
                super.addColumn(col);
            }
        };

        javax.swing.table.TableColumnModel modeloCabsFilas = new javax.swing.table.DefaultTableColumnModel() {
            boolean primeraCol = true;
            public void addColumn(javax.swing.table.TableColumn col) {
                if (primeraCol) {
                    col.setMaxWidth(65);
                    super.addColumn(col);
                    primeraCol = false;
                }
            }
        };

        javax.swing.table.TableModel modeloTabla = new CModeloTablaPrestamo();

        jtablaPrestamo = new javax.swing.JTable(modeloTabla, modeloColums);
        jtablaCabsFilas = new javax.swing.JTable(modeloTabla, modeloCabsFilas);

        jtablaPrestamo.createDefaultColumnsFromModel();
        jtablaCabsFilas.createDefaultColumnsFromModel();
        jtablaPrestamo.setSelectionModel(jtablaCabsFilas.getSelectionModel());

        jtablaCabsFilas.setBackground(java.awt.Color.lightGray);
        jtablaCabsFilas.setSelectionBackground(java.awt.Color.lightGray);

        jtablaPrestamo.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jtablaCabsFilas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);

        jScrollPane1.setViewportView(jtablaPrestamo);

        javax.swing.JViewport jv = new javax.swing.JViewport();
        jv.setView(jtablaCabsFilas);
        jv.setPreferredSize(jtablaCabsFilas.getMaximumSize());
        jScrollPane1.setRowHeader(jv);
        jScrollPane1.setCorner(javax.swing.JScrollPane.UPPER_LEFT_CORNER, jtablaCabsFilas.getTableHeader());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtfPeriodoMax = new javax.swing.JTextField();
        jtfPeriodoMin = new javax.swing.JTextField();
        jtfInteresMax = new javax.swing.JTextField();
        jtfInteresMin = new javax.swing.JTextField();
        jbtCalculoPagos = new javax.swing.JButton();
        jbtCalculoAmort = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jcbIncremento = new javax.swing.JComboBox<>();
        jtfCredito = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jmnuOpciones = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmItemSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmItemAños = new javax.swing.JMenuItem();
        JmItemMeses = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmItemInstruc = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Préstamo bancario");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Crédito");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Años de préstamo");

        jLabel3.setText("Máximo");

        jLabel4.setText("Mínimo");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Tipos de interés");

        jLabel6.setText("% máximo");

        jLabel7.setText("% mínimo");

        jLabel8.setText("Incremento");

        jtfPeriodoMax.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jtfPeriodoMax.setPreferredSize(new java.awt.Dimension(80, 20));
        jtfPeriodoMax.addActionListener(this::jtfPeriodoMaxActionPerformed);

        jtfPeriodoMin.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jtfPeriodoMin.setPreferredSize(new java.awt.Dimension(80, 20));

        jtfInteresMax.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        jtfInteresMin.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        jbtCalculoPagos.setText("Pagos");
        jbtCalculoPagos.setPreferredSize(new java.awt.Dimension(155, 26));
        jbtCalculoPagos.addActionListener(this::jbtCalculoPagosActionPerformed);

        jbtCalculoAmort.setText("Amortización");
        jbtCalculoAmort.setPreferredSize(new java.awt.Dimension(155, 26));
        jbtCalculoAmort.addActionListener(this::jbtCalculoAmortActionPerformed);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(290, 130));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jcbIncremento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0.10", "0.25", "0.50", "1.00" }));

        jLabel9.setText("Bryan David Gonzalez Sincal IVD 15");

        jMenu1.setMnemonic('O');
        jMenu1.setText("Opciones");

        jmItemSalir.setText("Salir");
        jmItemSalir.addActionListener(this::jmItemSalirActionPerformed);
        jMenu1.add(jmItemSalir);

        jmnuOpciones.add(jMenu1);

        jMenu2.setMnemonic('P');
        jMenu2.setText("Préstamo");

        jmItemAños.setText("Años");
        jmItemAños.addActionListener(this::jmItemAñosActionPerformed);
        jMenu2.add(jmItemAños);

        JmItemMeses.setText("Meses");
        JmItemMeses.addActionListener(this::JmItemMesesActionPerformed);
        jMenu2.add(JmItemMeses);

        jmnuOpciones.add(jMenu2);

        jMenu3.setText("Ayuda");

        jmItemInstruc.setText("Instrucciones");
        jmItemInstruc.addActionListener(this::jmItemInstrucActionPerformed);
        jMenu3.add(jmItemInstruc);

        jmnuOpciones.add(jMenu3);

        setJMenuBar(jmnuOpciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtCalculoAmort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtCalculoPagos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtfPeriodoMin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtfPeriodoMax, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtfInteresMax))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8))
                            .addGap(1, 1, 1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jcbIncremento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtfInteresMin, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                .addGap(55, 55, 55)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfPeriodoMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfPeriodoMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfInteresMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtfInteresMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jcbIncremento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jbtCalculoPagos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtCalculoAmort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfPeriodoMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPeriodoMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPeriodoMaxActionPerformed

    private void jbtCalculoPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCalculoPagosActionPerformed
        // TODO add your handling code here:
        try {
    if (jtfCredito.getText().trim().isEmpty() ||
        jtfPeriodoMin.getText().trim().isEmpty() ||
        jtfPeriodoMax.getText().trim().isEmpty() ||
        jtfInteresMax.getText().trim().isEmpty() ||
        jtfInteresMin.getText().trim().isEmpty()) {
        
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor llena todos los campos de texto.");
        return;
    }

    credito = Double.parseDouble(jtfCredito.getText());
    periodoMin = Integer.parseInt(jtfPeriodoMin.getText());
    periodoMax = Integer.parseInt(jtfPeriodoMax.getText());
    interesMax = Double.parseDouble(jtfInteresMax.getText());
    interesMin = Double.parseDouble(jtfInteresMin.getText());
    incremento = Double.parseDouble(jcbIncremento.getSelectedItem().toString());

    añosMeses = periodoMax - periodoMin + 1;
    tiposIntrs = (int) Math.round((interesMax - interesMin) / incremento) + 1;

    initTable(tiposIntrs, añosMeses + 1);

    double intrs = interesMin;
    for (int i = 0; i < tiposIntrs; i++) {
        jtablaCabsFilas.setValueAt(String.format("%.2f%%", intrs), i, 0);
        int j = 1;
        for (int p = periodoMin; p <= periodoMax; p++) {
            double r = (intrs / 100) / 12;
            int n = p * 12;
            double cuota = (r == 0) ? (credito / n) : (credito * r) / (1 - Math.pow(1 + r, -n));
            jtablaPrestamo.setValueAt(String.format("%.2f", cuota), i, j - 1);
            j++;
        }
        intrs += incremento;
    }
} catch (Exception ex) {
    javax.swing.JOptionPane.showMessageDialog(this, "Revisa que los campos tengan datos válidos.");
}
    }//GEN-LAST:event_jbtCalculoPagosActionPerformed

    private void JmItemMesesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmItemMesesActionPerformed
        // TODO add your handling code here:
        jmItemAños.setEnabled(true);
        JmItemMeses.setEnabled(false);
        jLabel2.setText("Meses de préstamo");
    }//GEN-LAST:event_JmItemMesesActionPerformed

    private void jmItemAñosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemAñosActionPerformed
        // TODO add your handling code here:
        jmItemAños.setEnabled(false);
        JmItemMeses.setEnabled(true);
        jLabel2.setText("Años de préstamo");
    }//GEN-LAST:event_jmItemAñosActionPerformed

    private void jbtCalculoAmortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCalculoAmortActionPerformed
        // TODO add your handling code here:
        int filaSel = jtablaPrestamo.getSelectedRow();
int colSel = jtablaPrestamo.getSelectedColumn();

if (filaSel == -1 || colSel == -1) {
    javax.swing.JOptionPane.showMessageDialog(this, "Por favor selecciona primero una celda de la tabla.");
    return;
}

try {
    double interes = interesMin + (filaSel * incremento);
    int plazo = periodoMin + colSel;
    double cuota = Double.parseDouble(jtablaPrestamo.getValueAt(filaSel, colSel).toString());
    
    boolean esModoMeses = !JmItemMeses.isEnabled();
    int totalMeses = esModoMeses ? plazo : plazo * 12;

    StringBuilder sb = new StringBuilder();
    sb.append(String.format("Tabla de Amortización para un préstamo de $%.2f\n", credito));
    sb.append(String.format("Tasa: %.2f%% | Plazo: %d %s | Cuota Mensual: $%.2f\n\n", 
            interes, plazo, (esModoMeses ? "meses" : "años"), cuota));
    sb.append(String.format("%-6s | %-12s | %-12s | %-12s\n", "Mes", "Interés", "Capital", "Saldo Pend."));
    sb.append("-----------------------------------------------------------\n");

    double saldo = credito;
    double r = (interes / 100) / 12;

    for (int m = 1; m <= totalMeses; m++) {
        double intMes = saldo * r;
        double capMes = cuota - intMes;
        saldo -= capMes;
        if (saldo < 0) saldo = 0;

        sb.append(String.format("%-6d | $%-11.2f | $%-11.2f | $%-11.2f\n", m, intMes, capMes, saldo));
    }

    javax.swing.JTextArea textArea = new javax.swing.JTextArea(sb.toString());
    textArea.setRows(15);
    textArea.setColumns(45);
    textArea.setEditable(false);
    
    javax.swing.JScrollPane scroll = new javax.swing.JScrollPane(textArea);
    javax.swing.JOptionPane.showMessageDialog(this, scroll, "Tabla de Amortización", javax.swing.JOptionPane.INFORMATION_MESSAGE);

} catch (Exception ex) {
    javax.swing.JOptionPane.showMessageDialog(this, "Asegúrate de haber generado primero la tabla con el botón Pagos.");
}
    }//GEN-LAST:event_jbtCalculoAmortActionPerformed

    private void jmItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jmItemSalirActionPerformed

    private void jmItemInstrucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemInstrucActionPerformed
        // TODO add your handling code here:
    String mensaje = "Instrucciones de uso:\n\n"
        + "1. Selecciona la modalidad en el menú Préstamo (Años o Meses).\n"
        + "2. Ingrese el monto del crédito, el rango de períodos y el rango de tasas de interés.\n"
        + "3. Selecciona el incremento de interés deseado.\n"
        + "4. Haz clic en 'Pagos' para generar la tabla de cuotas mensuales.\n"
        + "5. Para ver el desglose de amortización de una opción, haz clic en una celda de la tabla y presiona 'Amortización'.";

    javax.swing.JOptionPane.showMessageDialog(this, mensaje, "Instrucciones", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jmItemInstrucActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new jfrmPrestamo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JmItemMeses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtCalculoAmort;
    private javax.swing.JButton jbtCalculoPagos;
    private javax.swing.JComboBox<String> jcbIncremento;
    private javax.swing.JMenuItem jmItemAños;
    private javax.swing.JMenuItem jmItemInstruc;
    private javax.swing.JMenuItem jmItemSalir;
    private javax.swing.JMenuBar jmnuOpciones;
    private javax.swing.JTextField jtfCredito;
    private javax.swing.JTextField jtfInteresMax;
    private javax.swing.JTextField jtfInteresMin;
    private javax.swing.JTextField jtfPeriodoMax;
    private javax.swing.JTextField jtfPeriodoMin;
    // End of variables declaration//GEN-END:variables
}
